[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "<NEWPROJECTNAME>"
description = "New project template"
version = '0.0.1'
requires-python = ">=3.9.12"
dependencies = []

[project.scripts]
<CMD> = "<NEWPROJECT>.__main__:main"