[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "audio_convert"
description = "Convert audio files"
version = '0.0.1'
requires-python = ">=3.9.12"
dependencies = [
    "click"
]

[project.scripts]
ac = "audio_convert.__main__:main"